services:

  quiz_db:
    image: "postgres:bullseye"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: crud_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crud_project
    networks:
      - pyquiz_net
    
  pyquiz:
    build: .
    ports:
      - "8000:80"
    networks:
      - pyquiz_net
    
    environment:
      DB_URL: quiz_db
    links:
      - quiz_db

networks:
  pyquiz_net: {}

